
project_id = "hhkabxkelgabcsczsljf"
[api]
enabled = true
[functions.generate-ideas]
verify_jwt = false
[functions.create-checkout-session]
verify_jwt = false
[functions.webhook-stripe]
verify_jwt = false
