
# This file tells Netlify how to handle your React Router routes

[build]
  publish = "dist"
  command = "npm run build"

# The following redirect rule ensures that all routes are redirected to index.html
# This allows React Router to handle the routing client-side
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Add headers to ensure proper caching behavior
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Add specific headers for static assets
[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

